# Workflow Trigger Contract
# Defines the API contract for triggering the campaign.build workflow

openapi: 3.1.0
info:
  title: Campaign Build Workflow API
  version: 1.0.0
  description: API for triggering and managing campaign build workflow runs

paths:
  /api/workflows/campaign.build/trigger:
    post:
      operationId: triggerCampaignBuild
      summary: Trigger a new campaign build workflow
      description: |
        Initiates a new workflow run for building a campaign with all required artifacts.
        For the minimal reference implementation, uses placeholder video URIs.
      tags:
        - Workflows
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CampaignBuildTriggerPayload'
            examples:
              minimalTrigger:
                summary: Minimal trigger for reference implementation
                value:
                  campaign_id: "test-campaign-001"
                  template_id: "collect_coins_v1"
                  difficulty: "medium"
                  theme: "neon_arcade"
                  assets:
                    logo_uri: "https://example.com/logo.png"
                    background_uri: "https://example.com/bg.png"
                  audio:
                    prompt: "upbeat electronic game music"
                    duration_sec: 60
                  intro_video_uri: "file:///fixtures/placeholder-intro.mp4"
                  outcome_win_uri: "file:///fixtures/placeholder-win.mp4"
                  outcome_lose_uri: "file:///fixtures/placeholder-lose.mp4"
                  rules:
                    win_score: 100
                    time_limit_sec: 45
      responses:
        '202':
          description: Workflow run accepted and queued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowRunResponse'
        '400':
          description: Invalid trigger payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '422':
          description: Validation error in payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'

  /api/workflows/runs/{runId}:
    get:
      operationId: getWorkflowRun
      summary: Get workflow run status
      tags:
        - Workflows
      parameters:
        - name: runId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Run status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowRunStatus'
        '404':
          description: Run not found

  /api/workflows/runs/{runId}/steps:
    get:
      operationId: getRunSteps
      summary: Get all steps for a workflow run
      tags:
        - Workflows
      parameters:
        - name: runId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of run steps
          content:
            application/json:
              schema:
                type: object
                properties:
                  steps:
                    type: array
                    items:
                      $ref: '#/components/schemas/RunStepStatus'

components:
  schemas:
    CampaignBuildTriggerPayload:
      type: object
      required:
        - campaign_id
        - template_id
        - difficulty
        - theme
        - audio
      properties:
        campaign_id:
          type: string
          description: Unique identifier for the campaign
          example: "campaign-2026-001"
        template_id:
          type: string
          description: Game template to use
          example: "collect_coins_v1"
        difficulty:
          type: string
          enum: [easy, medium, hard]
          description: Game difficulty level
        theme:
          type: string
          description: Visual theme for the campaign
          example: "neon_arcade"
        assets:
          type: object
          properties:
            logo_uri:
              type: string
              format: uri
            background_uri:
              type: string
              format: uri
        audio:
          type: object
          required:
            - prompt
            - duration_sec
          properties:
            prompt:
              type: string
              description: Description for audio generation
            duration_sec:
              type: number
              minimum: 10
              maximum: 300
        intro_video_uri:
          type: string
          format: uri
          description: Placeholder intro video URI
        outcome_win_uri:
          type: string
          format: uri
          description: Placeholder win outcome video URI
        outcome_lose_uri:
          type: string
          format: uri
          description: Placeholder lose outcome video URI
        rules:
          type: object
          properties:
            win_score:
              type: number
            time_limit_sec:
              type: number
            max_plays_per_user:
              type: number

    WorkflowRunResponse:
      type: object
      properties:
        run_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [queued, running]
        workflow_name:
          type: string
        workflow_version:
          type: string
        created_at:
          type: string
          format: date-time

    WorkflowRunStatus:
      type: object
      properties:
        id:
          type: string
          format: uuid
        workflow_name:
          type: string
        workflow_version:
          type: string
        status:
          type: string
          enum: [queued, running, completed, failed, cancelled]
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        error:
          type: string
        artifacts:
          type: array
          items:
            $ref: '#/components/schemas/ArtifactRef'

    RunStepStatus:
      type: object
      properties:
        step_id:
          type: string
        skill_id:
          type: string
        status:
          type: string
          enum: [pending, running, completed, failed, skipped]
        input_hash:
          type: string
        cache_hit:
          type: boolean
        duration_ms:
          type: number
        error:
          type: string
        output_artifact_ids:
          type: array
          items:
            type: string
            format: uuid

    ArtifactRef:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: "json/game-config"
        uri:
          type: string
          format: uri
        content_hash:
          type: string

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: number
        message:
          type: string
        error:
          type: string

    ValidationErrorResponse:
      type: object
      properties:
        statusCode:
          type: number
        message:
          type: array
          items:
            type: string
        error:
          type: string
