#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  -- Grant usage on schema (required to access any objects in the schema)
  GRANT USAGE ON SCHEMA $APP_SCHEMA TO $APP_DB_USER;

  -- Current permissions on existing objects in app schema
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $APP_SCHEMA TO $APP_DB_USER;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA $APP_SCHEMA TO $APP_DB_USER;

  -- DEFAULT PRIVILEGES: ensures future objects are accessible to app_user
  -- Omit FOR ROLE to apply to current user (\$POSTGRES_USER)
  ALTER DEFAULT PRIVILEGES IN SCHEMA $APP_SCHEMA
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_DB_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA $APP_SCHEMA
    GRANT USAGE, SELECT ON SEQUENCES TO $APP_DB_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA $APP_SCHEMA
    GRANT EXECUTE ON FUNCTIONS TO $APP_DB_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA $APP_SCHEMA
    GRANT EXECUTE ON ROUTINES TO $APP_DB_USER;
EOSQL
