import type { WorkflowSpec } from '../interfaces/workflow-spec.interface';
import { inputSelector, fromTrigger, fromStep, constant } from './input-helpers';

export const campaignBuildWorkflow: WorkflowSpec = {
  workflowName: 'campaign.build',
  version: '1.0.0',
  description: 'End-to-end campaign build from brief - generates complete campaign with all assets',
  steps: [
    {
      stepId: 'plan',
      skillId: 'campaign_plan_from_brief',
      dependsOn: [],
      description: 'Generate campaign plan from creative brief',
      inputSelector: inputSelector({
        brief: fromTrigger('brief'),
        brand_assets: fromTrigger('brand_assets'),
        constraints: fromTrigger('constraints'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 1000 },
    },
    {
      stepId: 'intel_plan',
      skillId: 'intelligence_plan',
      dependsOn: [],
      description: 'Generate template recommendation, theme, and prize tiers from brief',
      inputSelector: inputSelector({
        brief: fromTrigger('brief'),
        constraints: fromTrigger('constraints'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 1000 },
    },
    {
      stepId: 'intel_theme_brief',
      skillId: 'extract_theme_from_brief',
      dependsOn: [],
      description: 'Extract color theme from brief text',
      inputSelector: inputSelector({
        brief: fromTrigger('brief'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 1000 },
    },
    {
      stepId: 'intel_copy',
      skillId: 'generate_campaign_copy',
      dependsOn: ['plan'],
      description: 'Generate copy variations for headline, CTA, win/lose messages',
      inputSelector: inputSelector({
        campaign_context: fromStep('plan', 'data'),
        copy_types: constant('headline,subheadline,cta_button,win_message,lose_message,instructions'),
        tone: fromTrigger('tone'),
        variations_count: constant(3),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 1000 },
    },
    {
      stepId: 'intro_image',
      skillId: 'generate_intro_image',
      dependsOn: ['plan'],
      description: 'Generate intro image based on campaign plan',
      inputSelector: inputSelector({
        prompt: fromStep('plan', 'data.video_prompts[0].prompt'),
        brand_assets: fromTrigger('brand_assets'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 2000 },
    },
    {
      stepId: 'intel_theme_image',
      skillId: 'extract_theme_from_image',
      dependsOn: ['intro_image'],
      description: 'Extract color theme from generated intro image',
      inputSelector: inputSelector({
        image_uri: fromStep('intro_image', 'data.image_uri'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 1000 },
    },
    {
      stepId: 'intro_button_segmentation',
      skillId: 'segment_start_button',
      dependsOn: ['intro_image', 'plan'],
      description: 'Detect and segment start button in intro image',
      inputSelector: inputSelector({
        image_uri: fromStep('intro_image', 'data.image_uri'),
        button_hint: fromStep('plan', 'data.copy.cta_text'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 1000 },
    },
    {
      stepId: 'intro_video',
      skillId: 'generate_intro_video_loop',
      dependsOn: ['intro_image', 'plan'],
      description: 'Generate looping intro video from intro image',
      inputSelector: inputSelector({
        image_uri: fromStep('intro_image', 'data.image_uri'),
        motion_prompt: fromStep('plan', 'data.video_prompts[0].style_notes'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 3000 },
    },
    {
      stepId: 'bgm',
      skillId: 'generate_bgm_track',
      dependsOn: ['plan'],
      description: 'Generate background music track',
      inputSelector: inputSelector({
        style: fromStep('plan', 'data.audio_specs'),
        duration_sec: constant(30),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 2000 },
    },
    {
      stepId: 'sfx',
      skillId: 'generate_sfx_pack',
      dependsOn: ['plan'],
      description: 'Generate sound effects pack for game',
      inputSelector: inputSelector({
        sfx_list: fromStep('plan', 'data.audio_specs.sfx_list'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 2000 },
    },
    {
      stepId: 'audio_mix',
      skillId: 'mix_audio_for_game',
      dependsOn: ['bgm', 'sfx'],
      description: 'Mix and normalize audio tracks',
      inputSelector: inputSelector({
        bgm_uri: fromStep('bgm', 'data.audio_uri'),
        sfx_manifest: fromStep('sfx', 'data'),
        loudness_targets: constant({
          standard: 'lufs_14',
          bgm_lufs: -14,
          sfx_lufs: -12,
          true_peak_dbfs: -1,
        }),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 1000 },
    },
    {
      stepId: 'game_config',
      skillId: 'game_config_from_template',
      dependsOn: ['plan'],
      description: 'Generate game configuration from template',
      inputSelector: inputSelector({
        template_id: fromStep('plan', 'data.game_template.template_id'),
        theme: fromStep('plan', 'data.theme'),
        difficulty: fromStep('plan', 'data.difficulty'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 1000 },
    },
    {
      stepId: 'bundle_game',
      skillId: 'bundle_game_template',
      dependsOn: ['audio_mix', 'game_config'],
      description: 'Bundle game template with assets',
      inputSelector: inputSelector({
        template_id: fromStep('plan', 'data.game_template.template_id'),
        game_config: fromStep('game_config', 'data'),
        audio_uri: fromStep('audio_mix', 'data.output_dir'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 2000 },
    },
    {
      stepId: 'outcome_win',
      skillId: 'generate_outcome_video_win',
      dependsOn: ['plan'],
      description: 'Generate win outcome video',
      inputSelector: inputSelector({
        win_text: fromStep('plan', 'data.copy.win_message'),
        prompt: fromStep('plan', 'data.video_prompts[1].prompt'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 3000 },
    },
    {
      stepId: 'outcome_lose',
      skillId: 'generate_outcome_video_lose',
      dependsOn: ['plan'],
      description: 'Generate lose outcome video',
      inputSelector: inputSelector({
        lose_text: fromStep('plan', 'data.copy.lose_message'),
        prompt: fromStep('plan', 'data.video_prompts[2].prompt'),
      }),
      cachePolicy: { enabled: true, scope: 'run_only' },
      retryPolicy: { maxAttempts: 2, backoffMs: 3000 },
    },
    {
      stepId: 'manifest',
      skillId: 'assemble_campaign_manifest',
      dependsOn: ['intro_button_segmentation', 'intro_video', 'bundle_game', 'outcome_win', 'outcome_lose', 'intel_plan', 'intel_theme_brief', 'intel_copy', 'intel_theme_image'],
      description: 'Assemble final campaign manifest with all assets',
      inputSelector: inputSelector({
        campaign_id: fromTrigger('campaign_id'),
        campaign_name: fromTrigger('campaign_name'),
        intro_video_uri: fromStep('intro_video', 'data.video_uri'),
        win_video_uri: fromStep('outcome_win', 'data.video_uri'),
        lose_video_uri: fromStep('outcome_lose', 'data.video_uri'),
        game_bundle_uri: fromStep('bundle_game', 'data.bundle_uri'),
        button_bounds: fromStep('intro_button_segmentation', 'data.bounds'),
        intro_image: fromStep('intro_image', 'data.image_uri'),
        plan_data: fromStep('plan', 'data'),
        intel_plan_data: fromStep('intel_plan', 'data'),
        intel_theme_brief_data: fromStep('intel_theme_brief', 'data'),
        intel_copy_data: fromStep('intel_copy', 'data'),
        intel_theme_image_data: fromStep('intel_theme_image', 'data'),
      }),
      cachePolicy: { enabled: false, scope: 'run_only' },
      retryPolicy: { maxAttempts: 1, backoffMs: 1000 },
    },
    {
      stepId: 'qa_bundle',
      skillId: 'validate_game_bundle',
      dependsOn: ['bundle_game'],
      description: 'Validate game bundle for quality and completeness',
      inputSelector: inputSelector({
        bundle_uri: fromStep('bundle_game', 'data.bundle_uri'),
        checks: constant({
          verify_structure: true,
          verify_manifest: true,
          verify_assets: true,
          verify_config: true,
        }),
      }),
      cachePolicy: { enabled: false, scope: 'run_only' },
      retryPolicy: { maxAttempts: 1, backoffMs: 1000 },
    },
    {
      stepId: 'review_smoke',
      skillId: 'review_asset_quality',
      dependsOn: ['manifest'],
      description: 'Optional smoke test review of final campaign',
      inputSelector: inputSelector({
        artifact_refs: constant([{ uri: 'campaign_manifest', type: 'json', name: 'Campaign Manifest' }]),
        rubric_id: constant('general'),
      }),
      cachePolicy: { enabled: false, scope: 'run_only' },
      retryPolicy: { maxAttempts: 1, backoffMs: 1000 },
    },
  ],
};
